/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class beyond_HelloWorldJNI */

#ifndef _Included_beyond_HelloWorldJNI
#define _Included_beyond_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     beyond_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_beyond_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
